
CREATE TABLE USUARIO (
    NICKNAME varchar (20),
    NOMBRE_APELLIDO varchar(100) NOT NULL,
    EMAIL varchar (50) NOT NULL,
    PASSWORD varchar (50) NOT NULL,
    PRIMARY KEY (NICKNAME)
);

CREATE TABLE GENERO (
    ID INT AUTO_INCREMENT,
    DESCRIPCION varchar(100) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CANCION(
    ID INT AUTO_INCREMENT,
    NOMBRE varchar(100),
    AUTOR varchar(100),
    NICKNAME varchar(20),
    GENERO_ID INT,
    PRIMARY KEY(ID)
);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_usuario
FOREIGN KEY (NICKNAME) REFERENCES USUARIO(NICKNAME);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_genero
FOREIGN KEY (GENERO_ID) REFERENCES GENERO(ID);

CREATE TABLE LISTA_REPRODUCCION (
    ID INT AUTO_INCREMENT,
    DESCRIPCION varchar(100),
    NICKNAME varchar(20),
    PRIMARY KEY(ID)
);

ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT fk_lista_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

CREATE TABLE LISTA_CANCION(
    LISTA_ID INT,
    CANCION_ID INT
);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT pk_lista_cancion
PRIMARY KEY (LISTA_ID, CANCION_ID);

alter TABLE LISTA_CANCION ADD CONSTRAINT fk_lista_listar
FOREIGN KEY(LISTA_ID) REFERENCES LISTA_REPRODUCCION(ID);

alter TABLE LISTA_CANCION ADD CONSTRAINT fk_lista_cancion
FOREIGN KEY(CANCION_ID) REFERENCES CANCION(ID);

--DML
insert into USUARIO values ('moios', 'Moi Avalos', 'moios@gmail.com','12345');
insert into USUARIO values ('pepe','El pepe', 'elpepe@gmail.com','456789');

update USUARIO
   set NOMBRE_APELLIDO= 'Moises Avalos'
 where NICKNAME like 'moios';

 select * from USUARIO;
 select EMAIL from USUARIO where NICKNAME like 'moios';

 delete from USUARIO
  where NICKNAME= 'pepe';